version: "3.8"

services:
  db:
    container_name: db
    build:
      context: ./server/db
      dockerfile: Dockerfile.dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./server/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      start_period: 10s
      timeout: 4s
      retries: 3

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./server/db/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    links:
      - server
  
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file:
      - server/.env
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy