version: "2"

services:
  client:
    image: markwbennett/ravel-platform_client:latest

  server:
    image: markwbennett/ravel-platform_server:latest
    env_file:
      - .env

  nginx:
    image: markwbennett/ravel-platform_nginx:latest
    restart: always
    ports:
      - "80:80"
