version: "2"

services:
  client:
    image: markwbennett/ravel-platform_client:latest

  server:
    image: markwbennett/ravel-platform_server:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ravel-platform-1.cgbsb1l0kytg.us-west-1.rds.amazonaws.com:5432/ravel

  nginx:
    image: markwbennett/ravel-platform_nginx:latest
    restart: always
    ports:
      - "80:80"
